
[
  {
    "id": "canada-2025-1",
    "piloto_participante": "George Russell",
    "equipo_participante": "Mercedes-AMG Petronas Formula One Team",
    "posicion": 1,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-2",
    "piloto_participante": "Max Verstappen",
    "equipo_participante": "Oracle Red Bull Racing",
    "posicion": 2,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-3",
    "piloto_participante": "Kimi Antonelli",
    "equipo_participante": "Mercedes-AMG Petronas Formula One Team",
    "posicion": 3,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-4",
    "piloto_participante": "Oscar Piastri",
    "equipo_participante": "McLaren Formula 1 Team",
    "posicion": 4,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-5",
    "piloto_participante": "Charles Leclerc",
    "equipo_participante": "Ferrari",
    "posicion": 5,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-6",
    "piloto_participante": "Lewis Hamilton",
    "equipo_participante": "Ferrari",
    "posicion": 6,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-7",
    "piloto_participante": "Fernando Alonso",
    "equipo_participante": "Aston Martin Aramco Formula One Team",
    "posicion": 7,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-8",
    "piloto_participante": "Nico Hülkenberg",
    "equipo_participante": "Stake F1 Team Kick Sauber",
    "posicion": 8,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-9",
    "piloto_participante": "Esteban Ocon",
    "equipo_participante": "Moneygram Haas F1 Team",
    "posicion": 9,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-10",
    "piloto_participante": "Carlos Sainz Jr",
    "equipo_participante": "Atlassian Williams Racing",
    "posicion": 10,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-11",
    "piloto_participante": "Oliver Bearman",
    "equipo_participante": "Moneygram Haas F1 Team",
    "posicion": 11,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-12",
    "piloto_participante": "Yuki Tsunoda",
    "equipo_participante": "Oracle Red Bull Racing",
    "posicion": 12,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-13",
    "piloto_participante": "Franco Colapinto",
    "equipo_participante": "BWT Alpine F1 Team",
    "posicion": 13,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-14",
    "piloto_participante": "Gabriel Bortoleto",
    "equipo_participante": "Stake F1 Team Kick Sauber",
    "posicion": 14,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-15",
    "piloto_participante": "Pierre Gasly",
    "equipo_participante": "BWT Alpine F1 Team",
    "posicion": 15,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-16",
    "piloto_participante": "Isack Hadjar",
    "equipo_participante": "Visa Cash App Racing Bulls F1 Team",
    "posicion": 16,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-17",
    "piloto_participante": "Lance Stroll",
    "equipo_participante": "Aston Martin Aramco Formula One Team",
    "posicion": 17,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "canada-2025-18",
    "piloto_participante": "Lando Norris",
    "equipo_participante": "McLaren Formula 1 Team",
    "posicion": 18,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": true,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": false
  },
  {
    "id": "canada-2025-19",
    "piloto_participante": "Liam Lawson",
    "equipo_participante": "Visa Cash App Racing Bulls F1 Team",
    "posicion": 19,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": true,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": false
  },
  {
    "id": "canada-2025-20",
    "piloto_participante": "Alexander Albon",
    "equipo_participante": "Atlassian Williams Racing",
    "posicion": 20,
    "ciudad_circuito": "Montreal",
    "year": 2025,
    "dnf": true,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": false
  }
]