
[
    {
      "id": "681b5e85bacce8731c2b6a85",
      "piloto_participante": "Lando Norris",
      "equipo_participante": "Mclaren Formula 1 Team",
      "posicion": 1,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a86",
      "piloto_participante": "Max Verstappen",
      "equipo_participante": "Oracle Red Bull Racing",
      "posicion": 2,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a87",
      "piloto_participante": "George Russell",
      "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
      "posicion": 3,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a88",
      "piloto_participante": "Kimi Antonelli",
      "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
      "posicion": 4,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a89",
      "piloto_participante": "Alexander Albon",
      "equipo_participante": "Atlassian Williams Racing",
      "posicion": 5,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a8a",
      "piloto_participante": "Lance Stroll",
      "equipo_participante": "Aston Martin Aramco Formula One Team",
      "posicion": 6,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a8b",
      "piloto_participante": "Nico Hülkenberg",
      "equipo_participante": "Stake F1 Team Kick Sauber",
      "posicion": 7,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a8c",
      "piloto_participante": "Charles Leclerc",
      "equipo_participante": "Scuderia Ferrari Hp",
      "posicion": 8,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a8d",
      "piloto_participante": "Oscar Piastri",
      "equipo_participante": "Mclaren Formula 1 Team",
      "posicion": 9,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a8e",
      "piloto_participante": "Lewis Hamilton",
      "equipo_participante": "Scuderia Ferrari Hp",
      "posicion": 10,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a8f",
      "piloto_participante": "Pierre Gasly",
      "equipo_participante": "Bwt Alpine F1 Team",
      "posicion": 11,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a90",
      "piloto_participante": "Yuki Tsunoda",
      "equipo_participante": "Oracle Red Bull Racing",
      "posicion": 12,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a91",
      "piloto_participante": "Esteban Ocon",
      "equipo_participante": "Moneygram Haas F1 Team",
      "posicion": 13,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a92",
      "piloto_participante": "Oliver Bearman",
      "equipo_participante": "Moneygram Haas F1 Team",
      "posicion": 14,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a93",
      "piloto_participante": "Isack Hadjar",
      "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
      "posicion": 15,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": true,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a94",
      "piloto_participante": "Liam Lawson",
      "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
      "posicion": 16,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": true,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a95",
      "piloto_participante": "Jack Doohan",
      "equipo_participante": "Bwt Alpine F1 Team",
      "posicion": 17,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": true,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a96",
      "piloto_participante": "Gabriel Bortoletto",
      "equipo_participante": "Stake F1 Team Kick Sauber",
      "posicion": 18,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": true,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a97",
      "piloto_participante": "Fernando Alonso",
      "equipo_participante": "Aston Martin Aramco Formula One Team",
      "posicion": 19,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": true,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681b5e85bacce8731c2b6a98",
      "piloto_participante": "Carlos Sainz Jr",
      "equipo_participante": "Atlassian Williams Racing",
      "posicion": 20,
      "ciudad_circuito": "Melbourne",
      "year": 2025,
      "dnf": true,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    }
  ]