[
  {
    "id": "681cd6108abbd581bdbcd9d3",
    "piloto_participante": "Lando Norris",
    "equipo_participante": "Mclaren Formula 1 Team",
    "posicion": 1,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9d1",
    "piloto_participante": "Oscar Piastri",
    "equipo_participante": "Mclaren Formula 1 Team",
    "posicion": 2,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9d5",
    "piloto_participante": "Lewis Hamilton",
    "equipo_participante": "Scuderia Ferrari Hp",
    "posicion": 3,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9e1",
    "piloto_participante": "Lance Stroll",
    "equipo_participante": "Aston Martin Aramco Formula One Team",
    "posicion": 5,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9d9",
    "piloto_participante": "Yuki Tsunoda",
    "equipo_participante": "Oracle Red Bull Racing",
    "posicion": 6,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9db",
    "piloto_participante": "Kimi Antonelli",
    "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
    "posicion": 7,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9d7",
    "piloto_participante": "Pierre Gasly",
    "equipo_participante": "Bwt Alpine F1 Team",
    "posicion": 8,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9e4",
    "piloto_participante": "Nico Hülkenberg",
    "equipo_participante": "Stake F1 Team Kick Sauber",
    "posicion": 9,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": false
  },
  {
    "id": "681cd6108abbd581bdbcd9dd",
    "piloto_participante": "Isack Hadjar",
    "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
    "posicion": 10,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9dc",
    "piloto_participante": "Alexander Albon",
    "equipo_participante": "Atlassian Williams Racing",
    "posicion": 11,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9d8",
    "piloto_participante": "Esteban Ocon",
    "equipo_participante": "Moneygram Haas F1 Team",
    "posicion": 12,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9e0",
    "piloto_participante": "Liam Lawson",
    "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
    "posicion": 13,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9da",
    "piloto_participante": "Oliver Bearman",
    "equipo_participante": "Moneygram Haas F1 Team",
    "posicion": 14,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9e2",
    "piloto_participante": "Gabriel Bortoletto",
    "equipo_participante": "Stake F1 Team Kick Sauber",
    "posicion": 15,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9de",
    "piloto_participante": "Jack Doohan",
    "equipo_participante": "Bwt Alpine F1 Team",
    "posicion": 16,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9d6",
    "piloto_participante": "Max Verstappen",
    "equipo_participante": "Oracle Red Bull Racing",
    "posicion": 17,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": false,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9df",
    "piloto_participante": "Fernando Alonso",
    "equipo_participante": "Aston Martin Aramco Formula One Team",
    "posicion": 18,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": true,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd6108abbd581bdbcd9e3",
    "piloto_participante": "Carlos Sainz Jr",
    "equipo_participante": "Atlassian Williams Racing",
    "posicion": 19,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": true,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": false
  },
  {
    "id": "681cd6108abbd581bdbcd9d4",
    "piloto_participante": "Charles Leclerc",
    "equipo_participante": "Scuderia Ferrari Hp",
    "posicion": 20,
    "ciudad_circuito": "Miami",
    "year": 2025,
    "dnf": true,
    "tipo": "Sprint",
    "categoria": "Formula 1",
    "estado": true
  }
]
