  [
    {
      "id": "681ccf0d616afdedb1fdbd50",
      "piloto_participante": "Max Verstappen",
      "equipo_participante": "Oracle Red Bull Racing",
      "posicion": 1,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd51",
      "piloto_participante": "Lando Norris",
      "equipo_participante": "Mclaren Formula 1 Team",
      "posicion": 2,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd52",
      "piloto_participante": "Oscar Piastri",
      "equipo_participante": "Mclaren Formula 1 Team",
      "posicion": 3,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd53",
      "piloto_participante": "Charles Leclerc",
      "equipo_participante": "Scuderia Ferrari Hp",
      "posicion": 4,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd54",
      "piloto_participante": "George Russell",
      "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
      "posicion": 5,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd55",
      "piloto_participante": "Kimi Antonelli",
      "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
      "posicion": 6,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd56",
      "piloto_participante": "Lewis Hamilton",
      "equipo_participante": "Scuderia Ferrari Hp",
      "posicion": 7,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd57",
      "piloto_participante": "Isack Hadjar",
      "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
      "posicion": 8,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd58",
      "piloto_participante": "Alexander Albon",
      "equipo_participante": "Atlassian Williams Racing",
      "posicion": 9,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd59",
      "piloto_participante": "Oliver Bearman",
      "equipo_participante": "Moneygram Haas F1 Team",
      "posicion": 10,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd5a",
      "piloto_participante": "Fernando Alonso",
      "equipo_participante": "Aston Martin Aramco Formula One Team",
      "posicion": 11,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd5b",
      "piloto_participante": "Yuki Tsunoda",
      "equipo_participante": "Oracle Red Bull Racing",
      "posicion": 12,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd5c",
      "piloto_participante": "Pierre Gasly",
      "equipo_participante": "Bwt Alpine F1 Team",
      "posicion": 13,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd5d",
      "piloto_participante": "Carlos Sainz Jr",
      "equipo_participante": "Atlassian Williams Racing",
      "posicion": 14,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd5e",
      "piloto_participante": "Jack Doohan",
      "equipo_participante": "Bwt Alpine F1 Team",
      "posicion": 15,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd5f",
      "piloto_participante": "Nico Hülkenberg",
      "equipo_participante": "Stake F1 Team Kick Sauber",
      "posicion": 16,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd60",
      "piloto_participante": "Liam Lawson",
      "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
      "posicion": 17,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd61",
      "piloto_participante": "Esteban Ocon",
      "equipo_participante": "Moneygram Haas F1 Team",
      "posicion": 18,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd62",
      "piloto_participante": "Gabriel Bortoletto",
      "equipo_participante": "Stake F1 Team Kick Sauber",
      "posicion": 19,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccf0d616afdedb1fdbd63",
      "piloto_participante": "Lance Stroll",
      "equipo_participante": "Aston Martin Aramco Formula One Team",
      "posicion": 20,
      "ciudad_circuito": "Suzuka",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    }
  ]

