  [
    {
      "id": "681cd02f658b76ac51d60226",
      "piloto_participante": "Oscar Piastri",
      "equipo_participante": "Mclaren Formula 1 Team",
      "posicion": 1,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60227",
      "piloto_participante": "George Russell",
      "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
      "posicion": 2,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60228",
      "piloto_participante": "Lando Norris",
      "equipo_participante": "Mclaren Formula 1 Team",
      "posicion": 3,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60229",
      "piloto_participante": "Charles Leclerc",
      "equipo_participante": "Scuderia Ferrari Hp",
      "posicion": 4,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d6022a",
      "piloto_participante": "Lewis Hamilton",
      "equipo_participante": "Scuderia Ferrari Hp",
      "posicion": 5,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d6022b",
      "piloto_participante": "Max Verstappen",
      "equipo_participante": "Oracle Red Bull Racing",
      "posicion": 6,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d6022c",
      "piloto_participante": "Pierre Gasly",
      "equipo_participante": "Bwt Alpine F1 Team",
      "posicion": 7,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d6022d",
      "piloto_participante": "Esteban Ocon",
      "equipo_participante": "Moneygram Haas F1 Team",
      "posicion": 8,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d6022e",
      "piloto_participante": "Yuki Tsunoda",
      "equipo_participante": "Oracle Red Bull Racing",
      "posicion": 9,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d6022f",
      "piloto_participante": "Oliver Bearman",
      "equipo_participante": "Moneygram Haas F1 Team",
      "posicion": 10,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60230",
      "piloto_participante": "Kimi Antonelli",
      "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
      "posicion": 11,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60231",
      "piloto_participante": "Alexander Albon",
      "equipo_participante": "Atlassian Williams Racing",
      "posicion": 12,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60232",
      "piloto_participante": "Isack Hadjar",
      "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
      "posicion": 13,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60233",
      "piloto_participante": "Jack Doohan",
      "equipo_participante": "Bwt Alpine F1 Team",
      "posicion": 14,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60234",
      "piloto_participante": "Fernando Alonso",
      "equipo_participante": "Aston Martin Aramco Formula One Team",
      "posicion": 15,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60235",
      "piloto_participante": "Liam Lawson",
      "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
      "posicion": 16,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60236",
      "piloto_participante": "Lance Stroll",
      "equipo_participante": "Aston Martin Aramco Formula One Team",
      "posicion": 17,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60237",
      "piloto_participante": "Gabriel Bortoletto",
      "equipo_participante": "Stake F1 Team Kick Sauber",
      "posicion": 18,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": false,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681cd02f658b76ac51d60238",
      "piloto_participante": "Carlos Sainz Jr",
      "equipo_participante": "Atlassian Williams Racing",
      "posicion": 19,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": true,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": false
    },
    {
      "id": "681cd02f658b76ac51d60239",
      "piloto_participante": "Nico Hülkenberg",
      "equipo_participante": "Stake F1 Team Kick Sauber",
      "posicion": 20,
      "ciudad_circuito": "Sakhir",
      "year": 2025,
      "dnf": true,
      "tipo": "Principal",
      "categoria": "Formula 1",
      "estado": false
    }
  ]