
  [
    {
      "id": "681ccd50616afdedb1fdbd14",
      "piloto_participante": "Lewis Hamilton",
      "equipo_participante": "Scuderia Ferrari Hp",
      "posicion": 1,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd15",
      "piloto_participante": "Oscar Piastri",
      "equipo_participante": "Mclaren Formula 1 Team",
      "posicion": 2,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd16",
      "piloto_participante": "Max Verstappen",
      "equipo_participante": "Oracle Red Bull Racing",
      "posicion": 3,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd17",
      "piloto_participante": "George Russell",
      "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
      "posicion": 4,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd18",
      "piloto_participante": "Charles Leclerc",
      "equipo_participante": "Scuderia Ferrari Hp",
      "posicion": 5,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd19",
      "piloto_participante": "Yuki Tsunoda",
      "equipo_participante": "Oracle Red Bull Racing",
      "posicion": 6,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd1a",
      "piloto_participante": "Kimi Antonelli",
      "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
      "posicion": 7,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd1b",
      "piloto_participante": "Lando Norris",
      "equipo_participante": "Mclaren Formula 1 Team",
      "posicion": 8,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd1c",
      "piloto_participante": "Lance Stroll",
      "equipo_participante": "Aston Martin Aramco Formula One Team",
      "posicion": 9,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd1d",
      "piloto_participante": "Fernando Alonso",
      "equipo_participante": "Aston Martin Aramco Formula One Team",
      "posicion": 10,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd1e",
      "piloto_participante": "Alexander Albon",
      "equipo_participante": "Atlassian Williams Racing",
      "posicion": 11,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd1f",
      "piloto_participante": "Pierre Gasly",
      "equipo_participante": "Bwt Alpine F1 Team",
      "posicion": 12,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd20",
      "piloto_participante": "Isack Hadjar",
      "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
      "posicion": 13,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd21",
      "piloto_participante": "Liam Lawson",
      "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
      "posicion": 14,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd22",
      "piloto_participante": "Oliver Bearman",
      "equipo_participante": "Moneygram Haas F1 Team",
      "posicion": 15,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd23",
      "piloto_participante": "Esteban Ocon",
      "equipo_participante": "Moneygram Haas F1 Team",
      "posicion": 16,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd24",
      "piloto_participante": "Carlos Sainz Jr",
      "equipo_participante": "Atlassian Williams Racing",
      "posicion": 17,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd25",
      "piloto_participante": "Gabriel Bortoletto",
      "equipo_participante": "Stake F1 Team Kick Sauber",
      "posicion": 18,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd26",
      "piloto_participante": "Nico Hülkenberg",
      "equipo_participante": "Stake F1 Team Kick Sauber",
      "posicion": 19,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    },
    {
      "id": "681ccd50616afdedb1fdbd27",
      "piloto_participante": "Jack Doohan",
      "equipo_participante": "Bwt Alpine F1 Team",
      "posicion": 20,
      "ciudad_circuito": "Shanghai",
      "year": 2025,
      "dnf": false,
      "tipo": "Sprint",
      "categoria": "Formula 1",
      "estado": true
    }
  ]

