[
  {
    "id": "681cd2e1658b76ac51d60262",
    "piloto_participante": "Oscar Piastri",
    "equipo_participante": "Mclaren Formula 1 Team",
    "posicion": 1,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60267",
    "piloto_participante": "Max Verstappen",
    "equipo_participante": "Oracle Red Bull Racing",
    "posicion": 2,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60265",
    "piloto_participante": "Charles Leclerc",
    "equipo_participante": "Scuderia Ferrari Hp",
    "posicion": 3,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60264",
    "piloto_participante": "Lando Norris",
    "equipo_participante": "Mclaren Formula 1 Team",
    "posicion": 4,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60263",
    "piloto_participante": "George Russell",
    "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
    "posicion": 5,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d6026c",
    "piloto_participante": "Kimi Antonelli",
    "equipo_participante": "Mercedes-Amg Petronas Formula One Team",
    "posicion": 6,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60266",
    "piloto_participante": "Lewis Hamilton",
    "equipo_participante": "Scuderia Ferrari Hp",
    "posicion": 7,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60274",
    "piloto_participante": "Carlos Sainz Jr",
    "equipo_participante": "Atlassian Williams Racing",
    "posicion": 8,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": true,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": false
  },
  {
    "id": "681cd2e1658b76ac51d6026d",
    "piloto_participante": "Alexander Albon",
    "equipo_participante": "Atlassian Williams Racing",
    "posicion": 9,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d6026e",
    "piloto_participante": "Isack Hadjar",
    "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
    "posicion": 10,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60270",
    "piloto_participante": "Fernando Alonso",
    "equipo_participante": "Aston Martin Aramco Formula One Team",
    "posicion": 11,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60271",
    "piloto_participante": "Liam Lawson",
    "equipo_participante": "Visa Cash App Racing Bulls Formula One Team",
    "posicion": 12,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d6026b",
    "piloto_participante": "Oliver Bearman",
    "equipo_participante": "Moneygram Haas F1 Team",
    "posicion": 13,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60269",
    "piloto_participante": "Esteban Ocon",
    "equipo_participante": "Moneygram Haas F1 Team",
    "posicion": 14,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60275",
    "piloto_participante": "Nico Hülkenberg",
    "equipo_participante": "Stake F1 Team Kick Sauber",
    "posicion": 15,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": true,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": false
  },
  {
    "id": "681cd2e1658b76ac51d60272",
    "piloto_participante": "Lance Stroll",
    "equipo_participante": "Aston Martin Aramco Formula One Team",
    "posicion": 16,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d6026f",
    "piloto_participante": "Jack Doohan",
    "equipo_participante": "Bwt Alpine F1 Team",
    "posicion": 17,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60273",
    "piloto_participante": "Gabriel Bortoletto",
    "equipo_participante": "Stake F1 Team Kick Sauber",
    "posicion": 18,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": false,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d6026a",
    "piloto_participante": "Yuki Tsunoda",
    "equipo_participante": "Oracle Red Bull Racing",
    "posicion": 19,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": true,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  },
  {
    "id": "681cd2e1658b76ac51d60268",
    "piloto_participante": "Pierre Gasly",
    "equipo_participante": "Bwt Alpine F1 Team",
    "posicion": 20,
    "ciudad_circuito": "Yeda",
    "year": 2025,
    "dnf": true,
    "tipo": "Principal",
    "categoria": "Formula 1",
    "estado": true
  }
]